server:
  port: 8081

spring:
  application:
    name: admin
  datasource:
    url: jdbc:mysql://dev:3306/zhflow?serverTimezone=GMT%2B8&useSSL=FALSE
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: dev
      port: 6379
      database: 1
      jedis:
        pool:
          # 连接池最大连接数（使用负值表示没有限制）
          max-active: 50
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: 3000ms
          # 连接池中的最大空闲连接数
          max-idle: 20
          # 连接池中的最小空闲连接数
          min-idle: 5
      timeout: 5000ms     # 连接超时时间（毫秒）
      password: 123456

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
