server:
  port: 8081

spring:
  application:
    name: admin
  cloud:
    compatibility-verifier:
      enabled: false

  banner:
    location: banner.txt

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    org.camunda: debug

security:
  permits:
    - /error/**
    - /api/admin/index/**
    - /api/admin/website/**
    - /api/admin/uiPage/getUiByCode/**
    - /api/security/validateToken**
    - /api/serviceThirdApp/**
    - /api/thirdApp/**
    - /api/admin/theme/getUseCss**

base-config:
  expire: 86400

camunda:
  bpm:
    authorization:
      tenant-check-enabled: false