server:
  port: 8081

spring:
  application:
    name: admin
  cloud:
    compatibility-verifier:
      enabled: false

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    org.camunda: debug

security:
  permits:
    - /error/**
    - /api/admin/index/**
    - /api/admin/website/**
    - /api/admin/uiPage/getUiByCode/**
    - /api/security/validateToken**
    - /api/third/**
  app-permits:
    - /api/proc/**
    - /api/admin/dict/**
    - /api/dept/**
    - /api/role/**
    - /api/user/**

base-config:
  expire: 86400
  third-app-id: 7CG1TlaLygU6hbQNhlzFU

camunda:
  bpm:
    authorization:
      tenant-check-enabled: false